#!/bin/bash

#############################################
# This is a simple battery warning script.  #
# It uses i3's nagbar to display warnings.  #
#                                           #
# @author agribu                            #
#############################################

# lock file location
export LOCK_FILE=/tmp/battery_state.lock

# check if another copy is running
if [[ -a $LOCK_FILE ]]; then

  pid=$(cat $LOCK_FILE | awk '{print $1}')
  ppid=$(cat $LOCK_FILE | awk '{print $2}')
  # validate contents of previous lock file
  vpid=${pid:-"0"}
  vppid=${ppid:-"0"}

  if (( $vpid < 2 || $vppid < 2 )); then
    # corrupt lock file $LOCK_FILE ... Exiting
    cp -f $LOCK_FILE ${LOCK_FILE}.`date +%Y%m%d%H%M%S`
    exit
  fi

  # check if ppid matches pid
  ps -f -p $pid --no-headers | grep $ppid >/dev/null 2>&1

  if [[ $? -eq 0 ]]; then
    # another copy of script running with process id $pid
    exit
  else
    # bogus lock file found, removing
    rm -f $LOCK_FILE >/dev/null
  fi

fi

pid=$$
ps -f -p $pid --no-headers | awk '{print $2,$3}' > $LOCK_FILE
# starting with process id $pid

# set Battery
BATTERY=$(ls /sys/class/power_supply/ | grep '^BAT')

# set full path
ACPI_PATH="/sys/class/power_supply/$BATTERY"

# get battery status
STAT=$(cat $ACPI_PATH/status)

# get remaining energy value
REM=`grep "POWER_SUPPLY_CHARGE_NOW" $ACPI_PATH/uevent | cut -d= -f2`

# get full energy value
FULL=`grep "POWER_SUPPLY_CHARGE_FULL_DESIGN" $ACPI_PATH/uevent | cut -d= -f2`

# get current energy value in percent
PERCENT=`echo $(( $REM * 100 / $FULL ))`

# set energy limit in percent, where warning should be displayed
WARN_LIMIT="20"

# Suspend limit
SUSPEND_LIMIT="15"

# Suspend command
SUSPEND_CMD="bash /home/fnivek/.dotfiles/my_configs/.i3/scripts/system suspend"

# set error message
MESSAGE="Warning power is ${PERCENT} will suspend at ${SUSPEND_LIMIT}!!!"

# show warning if energy limit in percent is less then user set limit and
# if battery is discharging
if [ "$STAT" == "Discharging" ]; then
  if [ $PERCENT -le "$(echo $WARN_LIMIT)" ] && [ $PERCENT -gt "$(echo $SUSPEND_LIMIT)" ]; then
    DISPLAY=:1 /usr/bin/i3-nagbar -t warning -m "$(echo $MESSAGE)"
  elif [ $PERCENT -le "$(echo $SUSPEND_LIMIT)" ]; then
    # dbus_session_file=~/.dbus/session-bus/$(cat /var/lib/dbus/machine-id)-0
    # if [ -e "$dbus_session_file" ]; then
    #   . "$dbus_session_file"
    #   export DBUS_SESSION_BUS_ADDRESS DBUS_SESSION_BUS_PID
    # fi
    # DISPLAY=:1 /usr/bin/i3-nagbar -m "$(echo $MESSAGE $DBUS_SESSION_BUS_ADDRESS)"
    $SUSPEND_CMD
  fi
fi
